// Generated by `pnpm measure --costs --write` from workers B and C on 2026-10-06. Do not edit.
// Each preset's work in hd-heavy-equivalent iterations (PLAN 6.2): its measured time minus the
// fixed overhead, relative to hd-heavy's, times hd-heavy's exact iteration count. Iteration
// counts alone miss per-sample costs: hd-fast costs about 1.4 times its iterations.
export const PRESET_COST = {
  "hd-fast": 1059129502,
  "hd-heavy": 3158889707,
} as const;
