// Generated by `pnpm calib:ref` (scripts/calib-ref.ts) from workloads/fractal. Do not edit.
// Re-run it after any change to workloads/fractal/fractal/core.py.

/** sha256 of the raw result (uint16 LE iteration counts) of each calibration view. */
export const CALIB_SHA256: readonly string[] = [
  "fd72c757097ae2cc888706e3fe4b33d82140b733a7c372086b465f9a9d41d24c",
  "1dc1a2ce33b6679987481ec74964e4137f89952266c2dd9483b1452f4ac3381a",
  "94c3a45326a4058ee7b5f40bf5d794ae685c1bc0703a42fc6f1c56f14de543f9",
  "7d00d5741c7b43bdd40e9bd72778d1713adb29fbd2de5ad24dbcfe372020f19b",
  "84e5d1e53604b6128f3795807d73afc90e0d610a133a451befd7a27f575e3c12",
  "7837ca11bfdfac9abe1b99f556e8573fa0aaa4d33d59506462d0fd742d16eb00",
  "d7aeb4224d60b5a1bca52c05b5388a3a3189cb6cdca434f94d7d2dab7c28065e",
  "e07349fd1bd678e8d678bfad429304867054b6686ee5d03ef60e285b3759c230",
];

/** Exact total iterations of each calibration view. */
export const CALIB_ITERS: readonly number[] = [
  103644355, 109992848, 250676354, 230833867, 144262132, 195604648, 186465843, 317181171,
];

/** Exact total iterations of each preset (the calib preset depends on its challenge). */
export const PRESET_ITERS = {
  tiny: 64,
  "hd-fast": 747314548,
  "hd-heavy": 3158889707,
} as const;

/** sha256 of workloads/fractal/fractal/core.py when these were generated. */
export const FRACTAL_SOURCE_SHA256 =
  "2f7a1b6a5b4a5263c5652c0f2b3971188c6aaef914efb795d5d8cf3f742538ff";
