// pnpm calib:ref
// Runs the fractal image for the 8 calibration views and every preset, then writes the
// reference hashes and exact iteration totals into packages/protocol (PLAN 6.2, 6.5).
// Integer arithmetic makes them identical on every CPU, so they are computed once and
// committed. Re-run it whenever workloads/fractal changes.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const image = process.env.FRACTAL_IMAGE || "pekkah/fractal:local";
const cpus = process.env.CALIB_CPUS || "4";

function sh(cmd: string, args: string[]): string {
  const r = spawnSync(cmd, args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (r.status !== 0) throw new Error(`${cmd} ${args[0]} failed:\n${r.stderr}`);
  return r.stdout;
}

function run(params: Record<string, unknown>): { sha256: string; iterations: number } {
  const out = mkdtempSync(join(tmpdir(), "pekkah-calib-"));
  chmodSync(out, 0o777);
  try {
    const stdout = sh("docker", [
      "run",
      "--rm",
      "--network",
      "none",
      "--read-only",
      "--tmpfs",
      "/tmp:rw,size=64m",
      "--cap-drop",
      "ALL",
      "--security-opt",
      "no-new-privileges",
      "--pids-limit",
      "256",
      "--user",
      "1000:1000",
      "-e",
      `WORKERS=${cpus}`,
      "-v",
      `${out}:/out`,
      image,
      JSON.stringify(params),
    ]);
    const match = /RESULT iterations=(\d+)/.exec(stdout);
    if (!match?.[1]) throw new Error(`no RESULT line for ${JSON.stringify(params)}`);
    const bytes = readFileSync(join(out, params.format === "raw" ? "result.bin" : "result.png"));
    return {
      sha256: createHash("sha256").update(bytes).digest("hex"),
      iterations: Number(match[1]),
    };
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
}

if (!process.argv.includes("--no-build")) {
  console.log(`building ${image}`);
  sh("docker", ["build", "-q", "-t", image, join(root, "workloads/fractal")]);
}

const sha256: string[] = [];
const iters: number[] = [];
for (let challenge = 0; challenge < 8; challenge++) {
  const r = run({ preset: "calib", challenge, format: "raw" });
  sha256.push(r.sha256);
  iters.push(r.iterations);
  console.log(`calib ${challenge}: ${r.iterations} iterations, sha256 ${r.sha256}`);
}
const presets: Record<string, number> = {};
for (const preset of ["tiny", "hd-fast", "hd-heavy"]) {
  presets[preset] = run({ preset, format: "raw" }).iterations;
  console.log(`${preset}: ${presets[preset]} iterations`);
}
// The timed calibration job (CALIBRATION.fractal's `rate` step): a real hd-fast render.
const rate = run({ preset: "hd-fast", palette: "ocean", format: "png" });
console.log(`rate (hd-fast, ocean, png): sha256 ${rate.sha256}`);

const sourceHash = createHash("sha256")
  .update(readFileSync(join(root, "workloads/fractal/fractal/core.py")))
  .digest("hex");

const file = `// Generated by \`pnpm calib:ref\` (scripts/calib-ref.ts) from workloads/fractal. Do not edit.
// Re-run it after any change to workloads/fractal/fractal/core.py.

/** sha256 of the raw result (uint16 LE iteration counts) of each calibration view. */
export const CALIB_SHA256: readonly string[] = ${JSON.stringify(sha256, null, 2)};

/** Exact total iterations of each calibration view. */
export const CALIB_ITERS: readonly number[] = ${JSON.stringify(iters)};

/** Exact total iterations of each preset (the calib preset depends on its challenge). */
export const PRESET_ITERS = ${JSON.stringify(presets, null, 2)} as const;

/** sha256 of the timed calibration render: hd-fast, palette ocean, PNG. */
export const CALIB_RATE_SHA256 = "${rate.sha256}";

/** sha256 of workloads/fractal/fractal/core.py when these were generated. */
export const FRACTAL_SOURCE_SHA256 = "${sourceHash}";
`;
const target = join(root, "packages/protocol/src/calibration-ref.ts");
writeFileSync(target, file);
sh(join(root, "node_modules/.bin/biome"), ["format", "--write", target]);
console.log(`wrote ${target}`);
