// pnpm measure [--workers B,C] [--presets hd-fast,hd-heavy]
// pnpm measure --costs [--workers B,C] [--write]
// PR-05 tuning on real hardware: dev-dispatches each preset to each calibrated worker on the
// deployed market, then prints the matcher's estimate next to the market-measured time and
// checks PLAN 6.3's rule for hd-heavy.
// --costs times hd-fast and hd-heavy on each worker (median of 3 runs, minus the median tiny
// run) and prints each preset's work relative to hd-heavy. --write stores the geometric mean
// across the workers in packages/protocol/src/calibration-cost.ts (PLAN 6.2).
// Reads PUBLIC_URL and DEMO_TOKEN from ~/.pekkah/env/market.env through the app's env loader;
// prints neither.
import { writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { estimateSec } from "../packages/matcher/src/index.js";
import {
  PRESET_ITERS,
  scenarioRequest,
  type WorkerSnapshot,
} from "../packages/protocol/src/index.js";
import { loadLocalEnv } from "../packages/runtime/src/index.js";

const { values } = parseArgs({
  options: {
    workers: { type: "string" },
    presets: { type: "string" },
    costs: { type: "boolean", default: false },
    write: { type: "boolean", default: false },
  },
});
process.env.PEKKAH_ENV_FILE ||= join(homedir(), ".pekkah", "env", "market.env");
loadLocalEnv();
const base = process.env.PUBLIC_URL?.replace(/\/+$/, "");
const token = process.env.DEMO_TOKEN;
if (!base || !token) {
  console.error("measure: market.env needs PUBLIC_URL and DEMO_TOKEN");
  process.exit(1);
}
const presets = (values.presets ?? "hd-fast,hd-heavy").split(",");
const wanted = values.workers?.split(",");

async function dispatch(workerId: string, params: Record<string, unknown>): Promise<number> {
  const res = await fetch(`${base}/api/dev/dispatch`, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
    body: JSON.stringify({ workerId, workload: "fractal", params }),
  });
  const body = (await res.json()) as { durationMs?: number; error?: string };
  if (!res.ok || body.durationMs === undefined) {
    throw new Error(`${workerId} ${String(params.preset)}: HTTP ${res.status} ${body.error ?? ""}`);
  }
  return body.durationMs / 1000;
}

const median = (xs: number[]) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)] ?? 0;

async function timed(workerId: string, params: Record<string, unknown>, runs: number) {
  const out: number[] = [];
  for (let i = 0; i < runs; i++) out.push(await dispatch(workerId, params));
  return median(out);
}

if (values.costs) {
  const ids = wanted ?? ["B", "C"];
  const preset = (name: "hd-fast" | "hd-heavy") => {
    const request = scenarioRequest(name === "hd-fast" ? "cpu-counter" : "cpu-tight");
    return request.workload === "fractal" ? { ...request.params } : {};
  };
  const jobs: [string, Record<string, unknown>, number][] = [
    ["hd-fast", preset("hd-fast"), 3],
    ["hd-heavy", preset("hd-heavy"), 3],
  ];
  // Workers run in parallel; each one runs its jobs one after another.
  const relative = await Promise.all(
    ids.map(async (id) => {
      const tiny = await timed(id, { preset: "tiny" }, 3);
      const work: Record<string, number> = {};
      for (const [name, params, runs] of jobs) {
        work[name] = Math.max((await timed(id, params, runs)) - tiny, 0.01);
      }
      const heavy = work["hd-heavy"] ?? 1;
      console.log(
        `${id}: tiny ${tiny.toFixed(3)} s, ${jobs.map(([n]) => `${n} ${work[n]?.toFixed(3)} s`).join(", ")}`,
      );
      return Object.fromEntries(jobs.map(([n]) => [n, (work[n] ?? 0) / heavy]));
    }),
  );
  const cost = (name: string) =>
    Math.round(
      Math.exp(relative.reduce((sum, r) => sum + Math.log(r[name] ?? 1), 0) / relative.length) *
        PRESET_ITERS["hd-heavy"],
    );
  const exact = (name: string) => PRESET_ITERS[name as keyof typeof PRESET_ITERS];
  console.log(`\n${"job".padEnd(10)}${"iterations".padEnd(14)}${"cost".padEnd(14)}cost/iterations`);
  for (const [name] of jobs) {
    console.log(
      `${name.padEnd(10)}${String(exact(name)).padEnd(14)}${String(cost(name)).padEnd(14)}${(cost(name) / exact(name)).toFixed(2)}`,
    );
  }
  if (values.write) {
    const file = resolve(import.meta.dirname, "../packages/protocol/src/calibration-cost.ts");
    writeFileSync(
      file,
      `// Generated by \`pnpm measure --costs --write\` from workers ${ids.join(" and ")} on ${new Date().toISOString().slice(0, 10)}. Do not edit.
// Each preset's work in hd-heavy-equivalent iterations (PLAN 6.2): its measured time minus the
// fixed overhead, relative to hd-heavy's, times hd-heavy's exact iteration count. Iteration
// counts alone miss per-sample costs: hd-fast costs about 1.4 times its iterations.
export const PRESET_COST = ${JSON.stringify({ "hd-fast": cost("hd-fast"), "hd-heavy": cost("hd-heavy") }, null, 2)} as const;
`,
    );
    console.log(`wrote ${file}`);
  }
  process.exit(0);
}

const workers = (await (await fetch(`${base}/api/workers`)).json()) as WorkerSnapshot[];
const rows: string[][] = [["worker", "preset", "est s", "actual s", "actual/est"]];
const est: Record<string, number> = {};
for (const w of workers) {
  if (wanted && !wanted.includes(w.workerId)) continue;
  if (w.status !== "online" || !w.calibration.fractal) {
    console.log(`skip ${w.workerId}: ${w.status}, calibrated ${!!w.calibration.fractal}`);
    continue;
  }
  for (const preset of presets) {
    const request = scenarioRequest(preset === "hd-fast" ? "cpu-counter" : "cpu-tight");
    if (request.workload !== "fractal") continue;
    request.params.preset = preset as typeof request.params.preset;
    const estimate = estimateSec(request, w) ?? Number.NaN;
    const res = await fetch(`${base}/api/dev/dispatch`, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
      body: JSON.stringify({ workerId: w.workerId, workload: "fractal", params: request.params }),
    });
    const body = (await res.json()) as { durationMs?: number; sha256?: string; error?: string };
    if (!res.ok || body.durationMs === undefined) {
      console.log(`${w.workerId} ${preset}: HTTP ${res.status} ${body.error ?? ""}`);
      continue;
    }
    const actual = body.durationMs / 1000;
    est[`${w.workerId}:${preset}`] = estimate;
    rows.push([
      w.workerId,
      preset,
      estimate.toFixed(1),
      actual.toFixed(1),
      (actual / estimate).toFixed(2),
    ]);
    console.log(
      `${w.workerId} ${preset}: est ${estimate.toFixed(1)} s, actual ${actual.toFixed(1)} s, sha256 ${body.sha256?.slice(0, 16)}`,
    );
  }
}
console.log("");
for (const row of rows) console.log(row.map((c) => c.padEnd(11)).join(""));
const h = (id: string) => est[`${id}:hd-heavy`];
const rule: [string, number | undefined, (v: number) => boolean][] = [
  ["est(B) <= 12 s", h("B"), (v) => v <= 12],
  ["est(A) <= 16 s", h("A"), (v) => v <= 16],
  ["est(C) >= 30 s", h("C"), (v) => v >= 30],
  ["est(C) <= 96 s", h("C"), (v) => v <= 96],
];
console.log("\nhd-heavy tuning rule (PLAN 6.3):");
for (const [name, value, ok] of rule) {
  console.log(
    `  ${name.padEnd(16)} ${value === undefined ? "not measured" : `${value.toFixed(1)} s  ${ok(value) ? "ok" : "FAILS"}`}`,
  );
}
